### ISSUE TITLE
Problem with snap (moved from #9)

### ISSUE THREAD

**Issue by nwg-piotr** [nwg-piotr/autotiling#13]
![Screenshot from 2020-06-28 06-13-07](https://user-images.githubusercontent.com/33443311/85933918-7dd0ce00-b906-11ea-82ce-97ab02633db2.png)

how i can load this ? 
installation by snap btw

_Originally posted by @mh4nx7net in https://github.com/nwg-piotr/autotiling/issues/9#issuecomment-650646845_

**Comment by nwg-piotr** [comment]
@morten-b

**Comment by morten-b** [comment]
I have made a new edge release. Could you give it a try with `snap install --edge  --devmode autotiling`

@mh4nx7net @ispanos

**Comment by ispanos** [comment]
> I have made a new edge release. Could you give it a try with `snap install --edge --devmode autotiling`
> 
> @mh4nx7net @ispanos

I tested it. Works fine.

**Comment by nwg-piotr** [comment]
Thanks to all.
