### ISSUE TITLE
Moving containers become stuck

### ISSUE THREAD

**Issue by travankor** [nwg-piotr/autotiling#19]
Testing autotile on the latest sway+wlroots git, I noticed that moving containers with the keyboard sometimes will be broken (moving containers with mouse still works). The only way to be able to move containers again is to kill the autotile script when this happens. Not sure how this happens exactly, but wanted to ask if anyone knows.

Running the manual version in case that's relevant.

**Comment by nwg-piotr** [comment]
Anyone else experienced such a behavior? More info needed.

**Comment by travankor** [comment]
Looking at the recent sway PR's, it seems like there are some regressions with i3 compatibility, so this might be the reason.

**Comment by nwg-piotr** [comment]
You mean: it only happens on the development version of sway?

**Comment by travankor** [comment]
No, I mean that there are some [regressions](https://github.com/swaywm/sway/issues/5754) in 1.5+ (1.5 was tagged in mid-July). But this is only noticed and getting fixed right now.

**Comment by nwg-piotr** [comment]
Ah, OK.

**Comment by jboyens** [comment]
I'm seeing the same thing on swaywm master as of the time of this message.

I've had to disable this to restore the functionality for the time being.

I did turn on debugging and the console just spits out `Debug: Switched to splitv` with each attempt to move a window. Windows that are in a stack seem to be able to move (once) and windows that are on separate outputs seem to be able to move from left to right across the monitor border (but not back left).

**Comment by jboyens** [comment]
I was unclear above.

When I said "windows that are in a stack", I meant windows that are in a splith together. The bottom window can move, but the top window cannot. I forgot about the explicit "stacking" support and that could be confusing for anyone else reading this.

**Comment by travankor** [comment]
Fixed with 1.6.
