### ISSUE TITLE
Feature-request: Flip existing layout when moving workspace to output in different orientation

### ISSUE THREAD

**Issue by cogitantium** [nwg-piotr/autotiling#21]
When spawning new containers, this project accounts for the output dimensions which are present at that given time. 

What I miss is autotiling 'reorienting' or rather flipping the configuration when moving a workspace from a workspace that is wide to one that is tall.

I'm not sure if this is a known bug or just behaviour that I experience, but the default binding for i3wm; `bindsym $mod+e layout toggle split`, does not flip the current container orientation when pressed after installing autotiling.

Interestingly, in0ni mentioned this recently: https://github.com/nwg-piotr/autotiling/issues/20#issuecomment-733456467

**Comment by nwg-piotr** [comment]
This is a very simple script. It does not measure the output dimensions, but only the ratio of the focused container height to its width. On this basis, it determines the further split orientation.

```python
new_layout = "splitv" if con.rect.height > con.rect.width else "splith"
```
It's not intended to do anything else.

**Comment by cogitantium** [comment]
That's fair, the feature doesn't necessarily have to be integrated into this. The script does rely indirectly on the output dimensions as that's the base for container size though.

However, the bug in autotiling disabling toggling the split orientation does seem relevant regardless of any new feature.

**Comment by nwg-piotr** [comment]
It's not a bug. It's a feature.

**Comment by GeneralDenmark** [comment]
Oh wow, I can't believe you've done this.

**Comment by nwg-piotr** [comment]
Have you read the description:

>This script uses the i3ipc-python library to switch the layout splith/splitv depending on the currently focused window dimensions. 

It does not promise anything else. Also what you call "the bug" does not happen on my laptop.
