### ISSUE TITLE
Install w/ snap not working

### ISSUE THREAD

**Issue by harshhhdev** [nwg-piotr/autotiling#24]
Trying to install with snap throws an error for 'autotiling' not found.

![image](https://user-images.githubusercontent.com/69592270/104492039-1546f700-55a1-11eb-99cc-94efc9caa246.png)

**Comment by nwg-piotr** [comment]
Sorry, this has nothing to do with the script. I don't package it for snap. I haven't used snap ever in my life. Ask @morten-b

**Comment by harshhhdev** [comment]
Yeah... I thought I should alert as in the readme it said that this can be installed via snap

**Comment by nwg-piotr** [comment]
The packager has been mentioned here, so should be aware of the issue from now on. Let's see what's going to happen.

**Comment by morten-b** [comment]
I had some difficulties making the snap work, without including certain development flags. Therefore it could not be published as stable, and I therefore removed it. Sorry for not having made a pull request earlier to edit the readme.md it is here now: https://github.com/nwg-piotr/autotiling/pull/25

**Comment by nwg-piotr** [comment]
@morten-b Thank you.
