### ISSUE TITLE
Resizing window doesn't update autotiling

### ISSUE THREAD

**Issue by mtshrmn** [nwg-piotr/autotiling#26]
**Steps to reproduce:**
(lets assume we have a regular monitor of 16x9 resolution)
1. open new window A
2. open new window B  (we now have two windows side by side with the width of 8 and a height of 9)
3. resize window B to be of width 10 (and a height of 9)
4. open new window C

**Current behavior** - window C opens in a horizontal configuration
**Expected behavior** - window C should open in a vertical configuration

This is happening because when resizing a window the event `Event.WINDOW_FOCUS` doesn't fire. There's no resize event in the API for a simple solution. Therefore I was able to "hack" it by adding another listener for the `Event.TICK` event and firing this event each time I resize a window. 

**NOTE:** This was tested on i3-gaps, but I assume it's no different in i3 or sway. 

i3 config snippet:
```conf
bindsym $mod+r resize set width 927 px; exec --no-startup-id i3-msg -t send_tick
```

source code manipulation:
```diff
diff --git a/autotiling/main.py b/autotiling/main.py
index 896034b..fae9164 100644
--- a/autotiling/main.py
+++ b/autotiling/main.py
@@ -114,6 +114,7 @@ def main():
     handler = partial(switch_splitting, debug=args.debug, workspaces=args.workspaces)
     i3 = Connection()
     i3.on(Event.WINDOW_FOCUS, handler)
+    i3.on(Event.TICK, handler)
     i3.main()
```

I'm submitting this issue because my solution is bad and hopefuly someone can find a better one.

**Comment by nwg-piotr** [comment]
Initially we did use `Event.BINDING`, but later it's been removed from the code. Wouldn't it be a kind of solution?

**Comment by mtshrmn** [comment]
Yes, no idea why I haven't thought of using it. Was there a reason to stop using `BINDING` in favor of `FOCUS`?

**Comment by nwg-piotr** [comment]
FOCUS has always been in use. BINDING was necessary on early versions of sway, but I don't remember the exact reason.
