### ISSUE TITLE
Autotiling does not start with sway but starting from terminal

### ISSUE THREAD

**Issue by nfm886** [nwg-piotr/autotiling#31]
Hi
Just installed autotiling. Added it to config and it does not start with session.
When I'm starting it from terminal, it works properly.
openSUSE Tumbleweed here.
Autotiling installed via pip but it also does not start installed manually.

#edit
Nevermind... It just started, ehh...

**Comment by nwg-piotr** [comment]
I never ever use pip, so no idea.

**Comment by heppenowski** [comment]
Try to say exact path to autotiling instead of `autotiling`
For example, `$HOME/.local/bin/autotiling` it should works.
