### ISSUE TITLE
Keybinding to cycle through all windows of a workspace

### ISSUE THREAD

**Issue by adigitoleo** [nwg-piotr/autotiling#35]
New to sway, used i3 briefly in the past but prefer dynamic tiling. This script gives me almost everything I need, except I can't figure out a way to get a key binding that just cycles focus through all windows of the current workspace. The `focus prev|next [sibling]` doesn't work like I want, I don't care about containers or stacks or whatever. I just want to cycle focus, in the forward and backward direction, through ALL windows of the workspace. If this isn't possible by default in sway (as I suspect), would it be something you'd be willing to implement here?

Thanks for making sway usable ;)

**Comment by nwg-piotr** [comment]
Haha, true. I couldn't get used to sway/i3 witout it. :)

I think what you want would be possible to achieve with some script. Not necessarily this certain one. I'll let you know when I have an idea.

**Comment by nwg-piotr** [comment]
Alright, this has already been done. See [this](https://gist.github.com/SidharthArya/f4d80c246793eb61be0ae928c9184406?permalink_comment_id=3134474#gistcomment-3134474). Works for me.
