### ISSUE TITLE
AUR versions not installable

### ISSUE THREAD

**Issue by dboneham** [nwg-piotr/autotiling#36]
I'm getting conflicts for the XLib and ipi3c packages with the versions already on my system (python 3.10)

**Comment by nwg-piotr** [comment]
Have you installed them with PIP? It's strongly discouraged.

**Comment by dboneham** [comment]
Doing a clean install of Arch on a new machine. I have got this line in my install notes:
sudo -H pip install psutil pyuv i3ipc requests

I think this was to install some dependencies relating to my status bar (bublebee-status)

**Comment by dboneham** [comment]
I uninstalled the above packages. Still a conflict with Xlib. Deleted Xlib (no idea what this is or what it does). Now autotiling installs.i have lost one module from the status bar (caffeine) which needed requests. Waiting to see what other damage I have done...

**Comment by nwg-piotr** [comment]
The `autotiling` package has one and only dependency: `python-i3ipc` module.

```
pkgname=('autotiling')
pkgver=1.6
pkgrel=2
pkgdesc="Script for sway and i3 to automatically switch the horizontal / vertical window split orientation"
arch=('x86_64')
url="https://github.com/nwg-piotr/autotiling"
license=('GPL3')
depends=('python-i3ipc')
makedepends=('python-setuptools' 'python-wheel')
source=("$pkgname-$pkgver.tar.gz::https://github.com/nwg-piotr/autotiling/archive/v$pkgver.tar.gz")

md5sums=('8fcbe5a35c0ff357dca6740e034cb216')

package() {
  cd "${pkgname}-${pkgver}"
  python setup.py install --root="${pkgdir}" --optimize=1
}
```

**Comment by dboneham** [comment]
Thanks for you help. It's working now.
