### ISSUE TITLE
update pypi pls? (1.1 → 1.6)

### ISSUE THREAD

**Issue by nobodyatandnothing** [nwg-piotr/autotiling#38]
https://pypi.org/project/autotiling/

**Comment by nwg-piotr** [comment]
LOL, the problem is that I never use PyPI. Someone requested adding autotiling there and led my hand, but I don't remember anything. Could maintaining the package be passed on anyone else?

**Comment by dpgraham4401** [comment]
I can set something up with GitHub actions that automatically publishes to PyPi whenever you tag a commit/release and push to GitHub. How does that sound @nwg-piotr?

**Comment by nwg-piotr** [comment]
Very well. I don't expect autotiling to have a lot of updates, as it's really a simple script, but feel free to do what's needed. I'm afk / on vacation, but I'll be back next week.

**Comment by dpgraham4401** [comment]
Woohoo! Thank you @nwg-piotr

**Comment by nwg-piotr** [comment]
It is solely your merit. :grin:
