### ISSUE TITLE
autotiling executable: permission denied

### ISSUE THREAD

**Issue by saltbr1nger** [nwg-piotr/autotiling#40]
Linux noob here, running Mint 20.3.

I moved the main.py into my /usr/bin directory and renamed it 'autotiling.'  i set my i3 config file to exec_always --no-startup-id autotiling, but my windows still load the old way.  When I type in 'autotiling' into my terminal, it tells me "Permission denied."  I have the i3ip-python dependency already installed.  Not sure what I'm doing wrong here.

**Comment by nwg-piotr** [comment]
You need to [change the file permissions](https://www.pluralsight.com/blog/it-ops/linux-file-permissions) to make it executable.

You may also do in from a file manager, like e.g. Thunar. Right-click the file name, select "Permissions" -> Allow this file to run as a program.

![image](https://user-images.githubusercontent.com/20579136/192654215-39a1809c-b628-428f-9b55-6f06d04ceacc.png)

**Comment by saltbr1nger** [comment]
Thanks man.  I made it executable (via terminal `chmod +x autotiling`) and it works now... but only when I manually launch autotiling from terminal.  In my i3 config file, I have  `exec_always --no-startup-id autotiling` which doesnt seem to be working.

**Comment by nwg-piotr** [comment]
If `autotiling` is on your `$PATH`, it must work.

**Comment by saltbr1nger** [comment]
I'm not sure.  I thought it has to be in /usr/bin to be executable, so i put it there.

**Comment by nwg-piotr** [comment]
One way or another, it has nothing to do with the script itself, but with your environment. Closing.
