### ISSUE TITLE
Doesn't start correctly with sway but starts in terminal

### ISSUE THREAD

**Issue by bruteforks** [nwg-piotr/autotiling#45]
not sure if this has to do with my setup (fedora) or what, but took awhile to figure out so maybe it helps someone else:

wouldn't execute when sway starts up, but would work when i executed autotiling from a terminal. found the tip on  [the inspiration repo](https://github.com/olemartinorg/i3-alternating-layout)

`exec_always ~/.local/bin/autotiling
`
now it works great

**Comment by Syphdias** [comment]
I would recommend `exec_always --no-startup-id`, since it is not a program you expect to ever see. `--no-startup-id` will disable the spinning cursor while it starts. https://i3wm.org/docs/userguide.html#exec

**Comment by nwg-piotr** [comment]
> exec_always --no-startup-id

This is irrelevant in sway.
