### ISSUE TITLE
Question : How to set minimum number of windows before triggering autotiling?

### ISSUE THREAD

**Issue by wSzki** [nwg-piotr/autotiling#49]
Hi, 

I'm confused regarding the usage of `-e`.
How could i use the `i3ipc` Enums to only trigger `autotiling` when there is a minimum of `n` windows in a workspace? 

Any pointers or examples would be appreciated.
Anyway thank you for this awesome program

**Comment by nwg-piotr** [comment]
You can't. This argument only determines which events will trigger `switch_splitting`.

There's no argument to do what you want. The `-l` argument will work in the opposite direction: disable autotiling after a number of containers reached.

**Comment by nwg-piotr** [comment]
Closing as answered.

**Comment by wSzki** [comment]
Thanks for the clarification 👍
