### ISSUE TITLE
Script not working properly on ultrawide monitors?

### ISSUE THREAD

**Issue by juipeltje** [nwg-piotr/autotiling#51]
hello,

i'm using 2 ultrawide monitors and tried to use autotiling with sway, but the container never starts vertical splitting until a third column is opened, even when i run it with `--limit 2`. i'm assuming this has something to do with how the script determines when to split based on width/height, and the extra width of an ultrawide monitor probably messes that up. is there anything that can be done to solve that? i do use dynamic tilers to solve this, but i still love i3/sway as well, but the manual tiling is killing me lol.

**Comment by Syphdias** [comment]
Hi @juipeltje, you are right; `--limit` is not the right tool for that. The way the script determines which way to split is by checking if the height of the window is bigger than the width.
https://github.com/nwg-piotr/autotiling/blob/31207c0ca44ed846763dc6df55316ee7a7d047a8/autotiling/main.py#L106
So with an ultra wide (21:9) the first two windows will be roughly 10.5:9, so still wider than high, thus resulting not in changing the split and affecting the next window.
PR #44 aims to make it configurable which `--splitratio`.

**Comment by juipeltje** [comment]
ah i see, thanks for explaining it. so the `--splitratio` feature still has to be implemented?

**Comment by nwg-piotr** [comment]
> ah i see, thanks for explaining it. so the `--splitratio` feature still has to be implemented?

Yeah, sorry for making you wait. I still have too many things to remember. I'll try to get back to it soon.

**Comment by juipeltje** [comment]
no worries, i was just a bit confused about whether it was implemented or not, but it's nice to hear that it's coming at some point in the future. i messed around with some other autotiling scripts that are out there as well, but they all seem to suffer from the same issues when used on an ultrawide monitor. in the meantime i'll try to get used to manual tiling :sweat_smile:

**Comment by nwg-piotr** [comment]
Personally I don't expect it to resolve the widescreen issue, but it's easy to test. Open the [merged version](https://gist.github.com/nwg-piotr/044779344398c1af42afd563fb9f480e) of the script, save somewhere on $PATH as e.g. `test-autotiling`, `pkill -f autotiling` and run the script you've just saved. Watch in the terminal what happens. Let me know.

**Comment by juipeltje** [comment]
i just tried the merged script, but like you said, the behaviour is still the same. i'm not getting much output from the terminal other than
```
 Event.WINDOW subscribed
 Event.MODE subscribed
```

**Comment by nwg-piotr** [comment]
For more output use the `--debug` flag. Not that it's gonna tell us something useful, but you'll see what's going on.

**Comment by nwg-piotr** [comment]
Give it a longer try, and then tell me your final opinion.

**Comment by juipeltje** [comment]
alright, will do, i'll keep using it and see what happens.

**Comment by juipeltje** [comment]
i just wanted to give a quick update after using the script for a few weeks now. so far i've only been using it with the `splitratio 1.61` option and i've been alternating between using it with and without the `--limit 2` option, to get a master stack and dwindle type layout. i haven't had any problems with it so far, but on two separate occasions it did spit out the following error in the terminal:
```
Error: 'NoneType' object has no attribute 'type'
```
so far i haven't been able to tell what triggers this error, since it only happened twice, but i thought maybe it was worth mentioning. i'm not entirely sure if that's a problem with the script or if i'm missing some sort of python module, cause i installed i3ipc in a python venv and use the script that way. this error hasn't had any effect on how the script functions from what i can tell. the autotiling still worked as expected even after the error.

**Comment by nwg-piotr** [comment]
If I understand well, you recommend to merge the changes, right?

**Comment by juipeltje** [comment]
yes, i would say it's good to go. i haven't tested every single option it has because i wouldn't use them normally, but it hasn't given me any trouble and has been working perfectly so far.

**Comment by Nama** [comment]
Came here looking for such a solution. The extra parameters look very useful, too.

**Comment by nwg-piotr** [comment]
Pending PR merged.
