### ISSUE TITLE
[Not a Bug] Crash when interactive resizing in i3

### ISSUE THREAD

**Issue by Syphdias** [nwg-piotr/autotiling#58]
Hey @nwg-piotr,

I just wanted to let you know — in case you don't already — that autotiling is affected by this i3 bug 
https://github.com/i3/i3/issues/5447

As far as I read the issue, this is not autotilings fault. Just something to be aware of.
So far, pressing <kbd>r</kbd> to recover worked every time without loosing windows.
I don't know if there is a way to work around [this](https://github.com/i3/i3/issues/5447#issuecomment-1493282195).

There are no open or closed issues with crash reports, so I assume nobody blames it on autotiling, if it happens.
You could add a know issue section linking to the issue in case it comes up.

**Comment by nwg-piotr** [comment]
Thank you for letting everyone know. I haven't uses i3 for years, to be honest.

**Comment by Syphdias** [comment]
Cannot image that sway coincidentally has the same bug.

I’ll close this issue.
