### ISSUE TITLE
Split Ratio under Sway

### ISSUE THREAD

**Issue by mrgreen3** [nwg-piotr/autotiling#60]
Am running Archlinux package 1.9.3-2

Autotiling works fine so I thought I would try the -sr option. Under Sway I cannot see any difference... Was hoping it worked in a similar way to DWM.

Unless I am looking at the incorrect option ;-)

Thanks

Mr Green

**Comment by nwg-piotr** [comment]
Hi,

You could try `autotiling -l 2 -sr 1.61`:

![obraz](https://github.com/user-attachments/assets/5c443c87-4a52-4835-95da-a268459984c4)

**Comment by mrgreen3** [comment]
In DWM the master window is slightly larger... Not sure if that is possible. The layout above is fine and I can live with it. As a rule I tend to have no more than two terminals open. After three things get a little tight ;-)

![2024-12-12T11:40:50,428110926+00:00](https://github.com/user-attachments/assets/08668f81-801b-42b2-b0ef-51cd6b4fb684)

**Comment by nwg-piotr** [comment]
True. I usually don't open more than 4 windows (dwindle) at a time even on my main 2K display. 

> In DWM the master window is slightly larger... Not sure if that is possible.

`-sr 1.61` should give you the "golden ratio", but feel free to use other values. :)

**Comment by mrgreen3** [comment]
I will call it resolved, can mess around with settings.... Thanks for your help ;-)

**Comment by nwg-piotr** [comment]
Any time, @mrgreen3!
