### ISSUE TITLE
Question : How do I remove/hide the border selector?

### ISSUE THREAD

**Issue by Ryuuusuke** [nwg-piotr/autotiling#61]
Hi! thank you for creating this script! 
i just realized that the border selector overwrite my border color. how do i remove/hide it?
thanks!
![image](https://github.com/user-attachments/assets/27f3c7d6-acdf-4f44-beca-ac3bfff8e325)

**Comment by nwg-piotr** [comment]
Hi,

As far as I know, this script does nothing to borders' settings. [Read this, please](https://github.com/nwg-piotr/autotiling?tab=readme-ov-file#please-do-read-this).

**Comment by Syphdias** [comment]
What you are seeing is the indicator where the next split will go. If you want to not see it, just set it to the same color as your border.

Here is the docs for that:
https://i3wm.org/docs/userguide.html#client_colors

**Comment by Ryuuusuke** [comment]
> What you are seeing is the indicator where the next split will go. If you want to not see it, just set it to the same color as your border.
> 
> Here is the docs for that: https://i3wm.org/docs/userguide.html#client_colors

Thank you for replying!
so its the indicator. I will read the link you sent me! i was searching in the google for ‘selector’ instead of ‘indicator’. i will try this and sorry for the long reply :(

**Comment by Ryuuusuke** [comment]
UPDATE : in 
          
``` <colorclass> <border> <background> <text> <indicator> <child_border> ```
```        client.focused #fca6ff #fca6ff #fca6ff           ```       

i only inserted 3 section so i added the  <indicator> #fca6ff also and now the selecto,,, i mean indicator is now the same color as my border color. i apologize for not reading the docs in detail and thank you for your support!
