### ISSUE TITLE
(sway) Incorrectly determines container as fullscreen

### ISSUE THREAD

**Issue by ammgws** [nwg-piotr/autotiling#7]
Lately I've found that autotiling isn't working in some situations. For example right now I have two monitors, with Firefox open on one workspace and a terminal open in the other. Opening some terminals on the Firefox workspace results in autotiling working correctly. However on the other workspace, autotiling does not work at all.

I added some extra debug output code to further investigate and found that non-fullscreen containers are being incorrectly flagged as being fullscreen. The screenshot shows 3 vertical containers side by side, and autotiling is reporting each of them as fullscreen:
![image](https://user-images.githubusercontent.com/20397027/78981928-f9b74780-7b5b-11ea-9689-cff273cccd8b.png)

I will look into it a bit further and possibly submit a patch.

**Comment by nwg-piotr** [comment]
Couldn't confirm here, so we need more info. Which version of python-i3ipc are you running?

**Comment by ammgws** [comment]
python-i3ipc 2.2.1-1 (https://www.archlinux.org/packages/community/any/python-i3ipc/)
Running sway-git.

After moving containers around randomly now even the other workspace is reporting everything as full screen. I'll look into it a bit more later.

**Comment by nwg-piotr** [comment]
Don't forget to take a closer look at your environment. On stable version of sway everything seems to work well.

**Comment by ammgws** [comment]
swaymsg returns `fullscreen_mode = 0` for the containers themselves, and `fullscreen_mode = 1` for the parent container, so that explains why autotiling is not working.

I can't find any recent commits in sway that may have changed the behaviour the below code relies on:
https://github.com/nwg-piotr/autotiling/blob/5370c92d4b86e327210337abe2fdbdc95957b92d/autotiling.py#L34-L35

I'll try with a release version of sway next.

**Comment by ammgws** [comment]
OK so I can also confirm it's working on sway 1.4:
![image](https://user-images.githubusercontent.com/20397027/78990919-9e448400-7b72-11ea-8818-8334e000dfcd.png)

Something has changed in sway between then and now. Next step is to check whether it's a bug or if it's working as intended.

**Comment by nwg-piotr** [comment]
Very well. The development version may or may not behave properly. I suggest to close the issue for now, and re-open if it appears again on next stable sway edition.

**Comment by ammgws** [comment]
Ok so let's remember to update this week the next sway release is out.
