### ISSUE TITLE
Problem moving windows after opened (using i3-gaps, 4.18)

### ISSUE THREAD

**Issue by Fuhrmann** [nwg-piotr/autotiling#8]
Thanks for your work! 

I have one little problem that all the others auto tiling scripts have: if I open a window, I have to press twice to move the window horizontally.

I'm using i3-gaps, 4.18.

Example in a clean workspace:

- Open window 1
- Open window 2
- They both open aside each other

```
|----------------| 
|        |       |
|   1    |  2    |
|        |       |
|----------------|
```

- Now, try to move window 2 to the left
- It doesnt move
- Try again and it moves

Could you try to reproduce this? Maybe it has to do with some of my configuration.

**Comment by hisacro** [comment]
I can reproduce.. gimmick of autotiling..

**Comment by nwg-piotr** [comment]
I confirm the misbehavior on i3. Haven't noticed it so far, since my main environment is sway. This needs a closer look.

**Comment by ammgws** [comment]
For me, on sway, on first try it moves the left window to the bottom and then on the second try it moves it to the left.

**Comment by nwg-piotr** [comment]
I don't really think this has something to do with the script itself. Surely I may be wrong.

**Comment by Fuhrmann** [comment]
I did try to reproduce the behavior of your script manually this way:

Using my split vertical shortcut:
`bindsym $mod+v split v`

Steps:

- Clean workspace;
- Open window 1;
- Open window 2;
- Press $mod+v to split v;
- Try to move focused window to left, it doesn't move because it is 'splittting?';
- Try again, it moves.

The problem occurs when splitting horizontally or vertically. So I guess it has to do wit i3 itself.

**Comment by nwg-piotr** [comment]
Quite what I was thinking about.

**Comment by Fuhrmann** [comment]
Since we already know this is not a problem with the script I'm closing. Thanks for the input!

**Comment by nwg-piotr** [comment]
Thank you for the submission. At least we already know more.

**Comment by hisacro** [comment]
@Fuhrmann it took a while but you can use something like this https://gitlab.com/qdak/i3-tools/-/blob/master/rotate_layout.py
```
bindsym $mod+u exec ~/Packages/i3-tools/rotate_layout.py 1
bindsym $mod+n exec ~/Packages/i3-tools/rotate_layout.py 0
```
this also works well with 3 windows autotile produce.
